#! /bin/sh.

python3 abc.py;
python3 blaze.py;
python3 bongino.py;
python3 breitbart.py;
python3 cbs.py;
python3 dailycaller.py;
python3 euronews.py;
python3 gbnews.py;
python3 globalnews.py;
python3 gript.py;
python3 gwp.py;
python3 pmillen.py;
python3 politico.py;
python3 revolver.py;
python3 rte.py;
python3 skyuk.py;
python3 spiked.py;
python3 timcast.py;
python3 vox.py;
python3 yahoo.py;
python3 zerohedge.py;