#! /bin/sh.

python3 ~/src/News-Aggregator/scripts/abc.py;
python3 ~/src/News-Aggregator/scripts/blaze.py;
python3 ~/src/News-Aggregator/scripts/bongino.py;
python3 ~/src/News-Aggregator/scripts/cbs.py;
python3 ~/src/News-Aggregator/scripts/beast.py
python3 ~/src/News-Aggregator/scripts/dailycaller.py;
python3 ~/src/News-Aggregator/scripts/euronews.py;
python3 ~/src/News-Aggregator/scripts/gbnews.py;
python3 ~/src/News-Aggregator/scripts/globalnews.py;
python3 ~/src/News-Aggregator/scripts/gript.py;
python3 ~/src/News-Aggregator/scripts/guardian.py;
python3 ~/src/News-Aggregator/scripts/gwp.py;
python3 ~/src/News-Aggregator/scripts/huff.py;
python3 ~/src/News-Aggregator/scripts/pmillen.py;
python3 ~/src/News-Aggregator/scripts/politico.py;
python3 ~/src/News-Aggregator/scripts/revolver.py;
python3 ~/src/News-Aggregator/scripts/rte.py;
python3 ~/src/News-Aggregator/scripts/skyuk.py;
python3 ~/src/News-Aggregator/scripts/spiked.py;
python3 ~/src/News-Aggregator/scripts/timcast.py;
python3 ~/src/News-Aggregator/scripts/vox.py;
python3 ~/src/News-Aggregator/scripts/yahoo.py;
python3 ~/src/News-Aggregator/scripts/zerohedge.py;
python3 ~/src/News-Aggregator/scripts/breit.py;
python3 ~/src/News-Aggregator/scripts/doubles.py;

#python3 ~/src/News-Aggregator/scripts/infowars.py;
#python3 ~/src/News-Aggregator/scripts/oan.py;
#python3 ~/src/News-Aggregator/scripts/amthinker.py;
#python3 ~/src/News-Aggregator/scripts/hill.py;
#python3 ~/src/News-Aggregator/scripts/npr.py;
#python3 ~/src/News-Aggregator/scripts/dailymail.py;
